language: node_js
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
node_js:
- iojs
after_success:
- npm run build && npm run deploy
env:
  global:
    GH_REF: github.com/garbados/chaiseblog.git
    secure: "YTaWwrotuiFDxuXMmwBSgO42uNYz4C6l1K401y1c394B6s79ZQC0ibhp+6m1xbMADWk9CEEE29nB+Rlf8ynfZp5Xjxp3KjM3kzib/NUDUl667h3iuN8rFiR1BSo5nvInpcGtOlfPMFJJsnESjqoL+JsbpOg7QArJNzXvSGAQXBM="
